# Generated by Django 2.1.3 on 2018-12-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=25)),
                ('class_of_student', models.CharField(max_length=25)),
            ],
        ),
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
